### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Stooovie** [einschmidt/addon-freshrss#13]
Hi, how do I install this? I tried copypasting the github URL as a HA addon repository as I always do, but that just returns "[URL] is not a valid addon repository". Thanks.

**Comment by einschmidt** [comment]
Hi @Stooovie 

The installation instructions are part of the DOCs file.

https://github.com/einschmidt/addon-freshrss/blob/main/freshrss/DOCS.md

Looking at your comment on the repository, I assume it works by now. So I will close this ticket for now.
Feel fry to reopen in case there are remaining questions.
