### ISSUE TITLE
Data Location

### ISSUE THREAD

**Issue by HydrelioxGitHub** [einschmidt/addon-freshrss#42]
I'm looking where fresh rss store data in HA. I just can't see anything with FreshRss name in my drive. Can you help me ? Thanks for your work btw.

**Comment by einschmidt** [comment]
Hi @HydrelioxGitHub 

The addon, like many other Home Assistant Addons, stores the data in a persistent folder:

```
/data
```

Each addon has its one data folder, and they are managed by the supervisor. Possible that they are managed at a dedicated volume.

Usually, there should be no reason to access these files. Is there any specific reason you want to access these files?

**Comment by HydrelioxGitHub** [comment]
Thanks for your quick answer. I'm facing a storage problem. Space disk keep reducing and I can't figure why. This come from one add-on as it stops when I deactivated all of them. I want to know how many space are taking each add-on to detect which one is so "space hungry".

**Comment by einschmidt** [comment]
Thanks for your explanation, as it helps to understand the problem. 

I had the same issue with any RSS addon. For the same reason, I exclude these types of addons also from backups. 

Now this brings me to some tips:

1. create a backup in home assistant. Download the file, extract and check the folders. It helps to find the causing addon. 
2. For freshrss, setup automatic deletion. For example, delete everything older than 14 days. I remember a default that never deleted anything. 

Hope these tips helped.

**Comment by HydrelioxGitHub** [comment]
I will also try to re-activate add-on one by one as the space disk keep decreasing almost constantly over time. I will try to spot which one is causing the issue.

**Comment by HydrelioxGitHub** [comment]
I think you can close this pseudo issue as you provide a good answer and advices. Thanks for your help !
