### ISSUE TITLE
Update to FreshRSS 1.22.1

### ISSUE THREAD

**Issue by Ovenlade** [einschmidt/addon-freshrss#43]
Hi!

Thank you for this great repository and the effort it took to set it all up! FreshRSS is my daily driver since it is so clean and customizable. Also love the dark mode themes. If I understand correctly, the login screen will be dark also after the update 🥇 

Could you please update FreshRSS?

Thanks in advance!

**Comment by einschmidt** [comment]
Hi @Ovenlade 

Thanks for describing how useful this addon is to you. As maintainer you sometimes forget or just don't know.

I have updated the add-on, using the latest versions.
